version: '2'
services:
    php:
        build: .
        links:
            - mysql
            - memcached
        volumes:
            - "./wp-content:/var/www/html/wp-content"
            - "./wp-config:/var/www/html/wp-config:ro"
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WP_DOMAIN: wp.local
            WP_ADMIN_USER: josh
            WP_EMAIL: j@joshbetz.com

    nginx:
        image: nginx:mainline
        volumes:
            - "./wp-content:/var/www/html/wp-content:ro"
            - ".docker/nginx.template:/etc/nginx/conf.d/wordpress.template:ro"
        volumes_from:
            - php:ro
        links:
            - php
        ports:
            - "80:8000"
        command: /bin/bash -c "envsubst '$$NGINX_PORT' < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        environment:
            NGINX_PORT: 8000

    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    memcached:
        image: memcached
